### ISSUE TITLE
Problem building rocm-device-libs

### ISSUE THREAD

**Issue by saitam757** [emaimx/Solus-ROCm-build#2]
I get an error when building rocm-device-libs. Below the output during build. Dependencies seems to be alright, but ROCM_DIR is missing:
All dependencies available:

`[BuildDep] Checking build-deps for rocm-device-libs-3.1.0-1
[BuildDep] Requesting installation of: llvm-roc, rocr-runtime-devel
Following packages will be installed:
llvm-roc  numactl  pciutils  rocr-runtime  rocr-runtime-devel  roct-thunk-interface`

Error:
`-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/lib64/ccache/bin/x86_64-solus-linux-gcc
-- Check for working C compiler: /usr/lib64/ccache/bin/x86_64-solus-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/bin/x86_64-solus-linux-g++
-- Check for working CXX compiler: /usr/lib64/ccache/bin/x86_64-solus-linux-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find ROCM (missing: ROCM_DIR)
CMake Error at CMakeLists.txt:44 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
`

**Comment by emaimx** [comment]
I cannot replicate the error. However when I built llvm-roc I had some issues with where the files were installed, that I fixed by editing directly the .eopkg because I didn't took one more night of compilation.

Can you check your llvm-roc .eopkg ? In the files.xml the files should be in /usr/lib64/llvm/roc/, mine where in something like /home/YPKG/intall/..... (I don't remember exactly).

**Comment by saitam757** [comment]
In my eopkg files are also path entries like yours. I think the problem is the usage of `-DCMAKE_INSTALL_PREFIX="$installdir/usr/lib64/llvm/roc"` in the package.yml files. I rember, I had also problems with this. From the [Solus packaging documentation](https://getsol.us/articles/packaging/package.yml/en/): 

> 

$installdir | The install directory, i.e. where files are installed to for packaging
-- | --

that means it is a temporary directory just for the building process, not the destination folder where the files should be after installation. I'm rebuilding llvm-roc with `-DCMAKE_INSTALL_PREFIX="%libdir%/usr/lib64/llvm/roc"` and see what happens.

**Comment by emaimx** [comment]
I think you are right, because %ninja_install is already a macro that is aware that we are installing in a chroot and overlay fs for packaging, so with that path we tell it 'inside the chroot, install the files in $installdir/.....' 

However, I think with `-DCMAKE_INSTALL_PREFIX="%libdir%/usr/lib64/llvm/roc"` you will get your files in `/usr/lib64/usr/lib64/llvm/roc`, and I think you should try `%libdir%/llvm/roc` or `/usr/lib64/llvm/roc`
